name: Terraform fmt check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v1.0.0
    - name: Terraform fmt -check
      run: |
        terraform fmt -check
